<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Authors>grittyfrog</Authors>
    <Company></Company>
    <Version>0.0.0.1</Version>
    <Description>Preview duty loot before it drops</Description>
    <Copyright></Copyright>
    <PackageProjectUrl>https://github.com/grittyfrog/DutyLootPreview</PackageProjectUrl>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aigamo.ResXGenerator" Version="4.4.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <ProjectReference Include="..\vendor\KamiToolKit\KamiToolKit.csproj" />
    <PackageReference Include="LuminaSupplemental.Excel" Version="4.3.4" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings.resx">
    </EmbeddedResource>
  </ItemGroup>

  <PropertyGroup>
    <ResXGenerator_NullForgivingOperators>true</ResXGenerator_NullForgivingOperators>
  </PropertyGroup>

  <PropertyGroup>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
</Project>
