//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutyLootPreview.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DutyLootPreview.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string DutyLoot_Filter_All {
            get {
                return ResourceManager.GetString("DutyLoot_Filter_All", resourceCulture)!;
            }
        }

        internal static string DutyLoot_Filter_Equipment {
            get {
                return ResourceManager.GetString("DutyLoot_Filter_Equipment", resourceCulture)!;
            }
        }

        internal static string DutyLoot_Filter_Favorites {
            get {
                return ResourceManager.GetString("DutyLoot_Filter_Favorites", resourceCulture)!;
            }
        }

        internal static string DutyLoot_Filter_Misc {
            get {
                return ResourceManager.GetString("DutyLoot_Filter_Misc", resourceCulture)!;
            }
        }

        internal static string DutyLoot_LoadingMessage {
            get {
                return ResourceManager.GetString("DutyLoot_LoadingMessage", resourceCulture)!;
            }
        }

        internal static string DutyLoot_NoItemsMessage {
            get {
                return ResourceManager.GetString("DutyLoot_NoItemsMessage", resourceCulture)!;
            }
        }

        internal static string DutyLoot_NoResultsMessage {
            get {
                return ResourceManager.GetString("DutyLoot_NoResultsMessage", resourceCulture)!;
            }
        }

        internal static string DutyLoot_Tooltip_InDutyButton {
            get {
                return ResourceManager.GetString("DutyLoot_Tooltip_InDutyButton", resourceCulture)!;
            }
        }

        internal static string DutyLoot_Tooltip_JournalButton {
            get {
                return ResourceManager.GetString("DutyLoot_Tooltip_JournalButton", resourceCulture)!;
            }
        }

        internal static string Title_DutyLootPreview {
            get {
                return ResourceManager.GetString("Title_DutyLootPreview", resourceCulture)!;
            }
        }
    }
}
